### ISSUE TITLE
It seems can't run in java8 or java 11 as well 它看起来并不能在java8或者java11中正常运行

### ISSUE THREAD

**Issue by KJZH001** [MohistMC/SodionAuth#37]
## There are some logs about This Plugin:
这里是一些关于本插件的log

```
[21:59:50 INFO]: [SodionAuth] Enabling SodionAuth v2.0-SNAPSHOT 
[21:59:50 INFO]: [SodionAuth] load 
[21:59:51 INFO]: [SodionAuth] Injecting com.google.guava:guava:29.0-jre 
[21:59:51 INFO]: [SodionAuth] Injecting com.google.guava:failureaccess:1.0.1 
[21:59:51 INFO]: [SodionAuth] Injecting com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava 
[21:59:51 INFO]: [SodionAuth] Injecting com.google.code.findbugs:jsr305:3.0.2 
[21:59:51 INFO]: [SodionAuth] Injecting org.checkerframework:checker-qual:2.11.1 
[21:59:51 INFO]: [SodionAuth] Injecting com.google.errorprone:error_prone_annotations:2.3.4 
[21:59:51 INFO]: [SodionAuth] Injecting com.google.j2objc:j2objc-annotations:1.3 
[21:59:51 INFO]: [SodionAuth] Relocating jdk:srczip:999 
[21:59:51 WARN]: java.lang.RuntimeException: Unable to relocate dependencies C:\Program Files\Java\jdk1.8.0_281\jre\..\src.zip 
[21:59:51 WARN]: 	at red.mohist.sodionauth.core.utils.dependency.DependencyManager.checkDependencyMaven(DependencyManager.java:136) 
[21:59:51 WARN]: 	at red.mohist.sodionauth.core.utils.Helper.<init>(Helper.java:76) 
[21:59:51 WARN]: 	at red.mohist.sodionauth.bukkit.BukkitLoader.onEnable(BukkitLoader.java:43) 
[21:59:51 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) 
[21:59:51 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) 
[21:59:51 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) 
[21:59:51 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) 
[21:59:51 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) 
[21:59:51 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) 
[21:59:51 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) 
[21:59:51 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) 
[21:59:51 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) 
[21:59:51 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) 
[21:59:51 WARN]: 	at java.lang.Thread.run(Thread.java:748) 
[21:59:51 WARN]: Caused by: java.io.FileNotFoundException: C:\Program Files\Java\jdk1.8.0_281\jre\..\src-relocated.jar (拒绝访问。) 
[21:59:51 WARN]: 	at java.io.FileOutputStream.open0(Native Method) 
[21:59:51 WARN]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270) 
[21:59:51 WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) 
[21:59:51 WARN]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) 
[21:59:51 WARN]: 	at me.lucko.jarrelocator.JarRelocator.run(JarRelocator.java:86) 
[21:59:51 WARN]: 	at red.mohist.sodionauth.core.utils.dependency.DependencyManager.checkDependencyMaven(DependencyManager.java:133) 
[21:59:51 WARN]: 	... 13 more 
[21:59:51 WARN]: [SodionAuth] SodionAuth load fail. 
[21:59:51 INFO]: Done (3.377s)! For help, type "help" or "?" 
[21:59:51 INFO]: Starting remote control listener 
[21:59:51 INFO]: RCON running on 0.0.0.0:55565 
[21:59:51 INFO]: Stopping server 
[21:59:51 INFO]: [SodionAuth] Disabling SodionAuth v2.0-SNAPSHOT 
[21:59:51 INFO]: [SodionAuth] Initializing threadPool service... 
[21:59:51 INFO]: [SodionAuth] Initializing eventBus service... 
[21:59:51 ERROR]: Error occurred while disabling SodionAuth v2.0-SNAPSHOT (Is it up to date?) 
>java.lang.NoClassDefFoundError: org/teasoft/bee/osql/NameTranslate 
at red.mohist.sodionauth.core.services.Service.<clinit>(Service.java:30) ~[?:?] 
at red.mohist.sodionauth.core.events.Event.post(Event.java:26) ~[?:?] 
at red.mohist.sodionauth.bukkit.BukkitLoader.onDisable(BukkitLoader.java:88) ~[?:?] 
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1618] 
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[patched_1.12.2.jar:git-Paper-1618] 
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.12.2.jar:git-Paper-1618] 
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424) ~[patched_1.12.2.jar:git-Paper-1618] 
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) ~[patched_1.12.2.jar:git-Paper-1618] 
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:363) ~[patched_1.12.2.jar:git-Paper-1618] 
at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486) ~[patched_1.12.2.jar:git-Paper-1618] 
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:702) ~[patched_1.12.2.jar:git-Paper-1618] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281] 
>Caused by: java.lang.ClassNotFoundException: org.teasoft.bee.osql.NameTranslate 
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_281] 
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1618] 
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618] 
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_281] 
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_281] 
... 12 more 
```

This log is run in Java 8 Environment，but run in java 11 also report same ERROR

这个是在java8中运行的log，在java11中运行也产生了同样（或类似）的错误

## 环境信息/Environment
OS Windows 10 pro
Core Paper for Minecraft 1.12.2
Plugin SodionAuth-2.0-Alpha.3-all/SodionAuth-Bukkit-2.0-Alpha.3-all

## 额外信息/Other Message
It also can't running on my BungeeCord Server

If you need log,please tell me.Then I will send it to the issue

它同样也不能在我的BungeeCord服务端上运行，如果你需要的log话请回复我，我会将它发送到这里

I'm sorry I can't speak English Well，thank you to read it to end

我很抱歉我英语水平并不太好，谢谢你能够阅读本文到结尾

**Comment by MAX-XiaoKui** [comment]
插件需要Java11啊，log里面显示的是Java8

**Comment by KJZH001** [comment]
> 插件需要Java11啊，log里面显示的是Java8

emmn...我放出来的log是java8没错

不过在Java11里运行的时候也产生了类似的错误

**Comment by MAX-XiaoKui** [comment]
看日志是Java的文件被拒绝访问
用管理员身份运行试试
或者换个Java，比如[AdoptOpenJDK](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot)

**Comment by ahdg6** [comment]
? 这个依赖是 SodionAuth 引入的，和Java没关系，导致插件无法启用的是某些依赖项未被正确处理，我也遇到过，自己去CI下了个Shaded-All的就好了，建议开发者检查相关代码

**Comment by ahdg6** [comment]
https://ci.ishland.com:43333/job/SodionAuth/lastSuccessfulBuild/artifact/SodionAuth-Relocate/build/libs/SodionAuth-Relocate-2.0-SNAPSHOT-all.jar

**Comment by ahdg6** [comment]
或者下那个 Lib ，然后手动覆盖进 Jar 包也能解决这个问题，具体什么原因我不清楚，但我这样解决了
